name: dart_application_1
description: An absolute bare-bones web app.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'



dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  dio: ^4.0.6
  lints: ^2.0.0
  shelf_router: ^1.1.3
dependencies: {http: ^0.13.5}
